### ISSUE TITLE
openvpn.exe is not added to PATH

### ISSUE THREAD

**Issue by CMCDragonkai** [wget/chocolatey_openvpn#13] opened 2020-01-13 04:59 UTC
I installed with:

```
choco install openvpn --params "'/SELECT_LAUNCH=0' /SELECT_PATH=1" --force
```

Then I run `refreshenv` or I go into a new terminal. The `openvpn.exe` is not added to PATH at all. The executable exists in `C:\Program Files\OpenVPN\bin` though.

**Comment by mattock** [comment] 2020-01-13 07:36
OpenVPN NSI installers have not added openvpn.exe to the PATH in a long while. This is because adding to PATH required a custom makensis build due to string length limitations. Without the custom makensis build some people's PATH could get truncated.

So, unless the Chocolatey package has had PATH management this is expected behavior.

**Comment by CMCDragonkai** [comment] 2020-01-13 10:06
Many other chocolatey tools create shims for CLI tools. Like see `bindtools-only` package.

Also the README for this package claims to update the PATH. So at least that should be cleared up!

**Comment by wget** [comment] 2022-03-27 20:46
Revived at https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/openvpn

Closing.

**Closed as completed by wget** 2022-03-27 20:46 UTC
